### ISSUE TITLE
Solutions already implemented

### ISSUE THREAD

**Issue by isakb** [rasmus4200/algorithms101#1]
While checking out https://www.udemy.com/data-structures-and-algorithms-bootcamp/learn/v4/t/lecture/8772568 I noticed that the code I was supposed to implement is already implemented.

I would propose removing the implementations from the the methods that should be part of the student exercises. The solutions could still be included in e.g. a different folder or separate branch of course.

**Comment by rasmus4200** [comment]
Good point isakb. I will add it to do the list and see if I can re-arrange things in some way to account for that. Stay tuned. And thank you for the feedback.

Cheers - Jonathan

**Comment by rasmus4200** [comment]
Hi isakb,

I haven't gone through the entire course yet, but I did [update the DynamicArray section](https://github.com/rasmus4200/algorithms101/commit/ba5c18de495f92a891483369659edd34688eeba5) to include stubbed out methods for students to try implementing the exercises before seeing the solution.

Thank you for the suggestion. I will update other sections when I have time. Let me know if you see any others.

Cheers - Jonathan

**Comment by isakb** [comment]
Thanks Jonathan, that is awesome!

Cheers,
Isak

**Comment by IgorMSiqueira** [comment]
I just started the course and what I did was I select all **methods** and created an interface using the **extract** option on Intellij, so the tests still compile but started to fail and all implementations were **cleared** for me to code 'em up from scratch. May be useful to someone else, i'm at the begining of the course but seems good to so far....

**Comment by jrasmusson** [comment]
That's a sweet hack @IgorMSiqueira . Thanks for sharing!
