### ISSUE TITLE
Can not run unit test to start the course!

### ISSUE THREAD

**Issue by NivoSh** [rasmus4200/algorithms101#2]
Hello,
I just registered for this course and I'm having trouble run any of the unit test and it's giving me the red circle by each one of the files I tried to take a screen shot but I couldn't attach it to my message.
SDK is been set up but still having problem.

Thanks

**Comment by rasmus4200** [comment]
Hello NivoSh,

Apologies for the unit tests not running. Were you able to resolve the problem?

Cheers - Jonathan

**Comment by rasmus4200** [comment]
Hi NivoSh,

One other thing to try is to see if you can create a new project with a single class and test.
If that works, you should be able to run the tests in the repos.

Let me know what error message you are getting and I will see if I can help.

Cheers - Jonathan
