### ISSUE TITLE
OneAway() method contains a bug.

### ISSUE THREAD

**Issue by YancongLi** [rasmus4200/algorithms101#3]
Relating to this challenge: There are three types of edits that can be performed on strings: insert a character, remove a character or replace a character. Given two strings, write a function to check if they are one or zero edits away.
A private method name OneEditReplace() is not working correctly because this line of code won't pass the test:
 
Assert.assertTrue(oneAwayDetector.oneAway("peter","peeer"));
or:
Assert.assertTrue(oneAwayDetector.oneAway("geaks","geeks"));

The correct implementation is:
private boolean OneEditReplace(String s1, String s2) {
        boolean foundDifference = false;
        for (int i = 0; i < s1.length(); i++) {
            if (s1.charAt(i) != s2.charAt(i)) {
                if (foundDifference) {
                    return false;
                }
                foundDifference = true;
            }
        }
        return true;
    }

👍

**Comment by jrasmusson** [comment]
Looks good YangongLi! Well done.
